import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import { NuqsAdapter } from 'nuqs/adapters/next';

import Header from '@/components/ui/header';
import LenisProvider from '@/components/providers/lenis';

import './globals.css';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Karvi autos',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <LenisProvider>
        <NuqsAdapter>
          <body
            className={`${raleway.variable} font-raleway antialiased h-dvh`}
          >
            <Header />
            {children}
          </body>
        </NuqsAdapter>
      </LenisProvider>
    </html>
  );
}
